{
 "title": "Solar Power System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Batterie",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltage{sensor=\"Batterie\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Input",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power{sensor=\"Solar\"}"
    }
   ]
  },
  {
   "title": "Output",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power{sensor=\"Consumer\"}"
    }
   ]
  },
  {
   "title": "Input Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(power{sensor=\"Solar\"}[$__range]) / count_over_time(power{sensor=\"Solar\"}[$__range])) / 1000"
    }
   ]
  },
  {
   "title": "Solar Sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "mamp" }
     ],
     "targets": [
      {
       "expr": "current{sensor=\"Solar\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "mvolt" }
     ],
     "targets": [
      {
       "expr": "voltage{sensor=\"Solar\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "mwatt" }
     ],
     "targets": [
      {
       "expr": "power{sensor=\"Solar\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batterie Sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "mamp" }
     ],
     "targets": [
      {
       "expr": "current{sensor=\"Batterie\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "mvolt" }
     ],
     "targets": [
      {
       "expr": "voltage{sensor=\"Batterie\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "mwatt" }
     ],
     "targets": [
      {
       "expr": "power{sensor=\"Batterie\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output Sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "mamp" }
     ],
     "targets": [
      {
       "expr": "current{sensor=\"Consumer\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "mvolt" }
     ],
     "targets": [
      {
       "expr": "voltage{sensor=\"Consumer\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "mwatt" }
     ],
     "targets": [
      {
       "expr": "power{sensor=\"Consumer\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "mamp" }
     ],
     "targets": [
      { "expr": "current", "legendFormat": "{{sensor}}" }
     ]
    },
    {
     "title": "Bus Voltage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "mvolt" }
     ],
     "targets": [
      { "expr": "voltage", "legendFormat": "{{sensor}}" }
     ]
    },
    {
     "title": "Power",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "mwatt" }
     ],
     "targets": [
      { "expr": "power", "legendFormat": "{{sensor}}" }
     ]
    }
   ]
  }
 ]
}